source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.2'
use_frameworks!

target 'TSActionSheet-Example' do
  pod "TSActionSheet", :path => "../../"
end

target 'TSActionSheet-ExampleTests' do
  pod "TSActionSheet", :path => "../../"
end
