
source 'https://github.com/CocoaPods/Specs.git'

target 'TSActionSheet-Example' do
  pod "TSActionSheet", :path => "../../"
end

target 'TSActionSheet-ExampleTests' do
  pod "TSActionSheet", :path => "../../"
end
